name: ReleaseCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: env
      #run: bash scripts/pipeline/release.sh aidenscratchprojects.riteshpripatel.com aidencode/html/aiden/index.html ${{ env.AWS_ACCESS_KEY}} ${{secrets.PROD_AWS_ACCESS_SECRET}} "index.html"
