name: release.spellingtest.riteshpripatel.com
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh spellingtest.riteshpripatel.com aidencode/html/spellingtest/index.html ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_ACCESS_SECRET}} "index.html"
